x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{2}:\d{2}:\d{2}.\d{3}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{2}:\d{2}:\d{2}.\d{3}) (?P<message>(?s:.*))$$'

version: "3.4"

services:
  app-a:
    build: ./fastapi_app/
    depends_on:
      - loki
    ports:
      - "8000:8000"
    logging: *default-logging
    environment:
      APP_NAME: "app-a"
      MODE: "grpc"
      COLLECTOR_ENDPOINT_GRPC_ENDPOINT: "jaeger-collector:14250"
  
  app-b:
    build: ./fastapi_app/
    depends_on:
      - loki
    ports:
      - "8001:8000"
    logging: *default-logging
    environment:
      APP_NAME: "app-b"
      MODE: "thrift-collector"
      COLLECTOR_THRIFT_URL: "http://jaeger-collector:14268"
  
  app-c:
    build: ./fastapi_app/
    depends_on:
      - loki
    ports:
      - "8002:8000"
    logging: *default-logging
    environment:
      APP_NAME: "app-c"
      MODE: "thrift-agent"
      AGENT_HOST_NAME: "jaeger-agent"
      AGENT_PORT: 6831

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.38.1
    command: 
      - "--reporter.grpc.host-port=jaeger-collector:14250"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
    depends_on:
      - jaeger-collector

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.38.1
    command: 
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
      - "--collector.zipkin.host-port=9411"
      - "--sampling.initial-sampling-probability=.5"
      - "--sampling.target-samples-per-second=.01"
    environment: 
      - SAMPLING_CONFIG_TYPE=adaptive
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14250"
      - "9411:9411"
    restart: on-failure
    depends_on:
      - cassandra-schema

  cassandra:
    image: cassandra:4.0

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:1.38.1
    depends_on:
      - cassandra

  jaeger-query:
    image: jaegertracing/jaeger-query:1.38.1
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
    ports:
      - "16686:16686"
      - "16687"
    restart: on-failure
    depends_on:
      - cassandra-schema

  grafana:
    image: grafana/grafana:9.1.7
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"

  loki:
    image: grafana/loki:2.6.1
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
