x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{2}:\d{2}:\d{2}.\d{3}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{2}:\d{2}:\d{2}.\d{3}) (?P<message>(?s:.*))$$'

version: "3.4"

services:
  app-a:
    build: ./fastapi_app/
    depends_on:
      - loki
    ports:
      - "8000:8000"
    logging: *default-logging
    environment:
      APP_NAME: "app-a"
      MODE: "otel-collector-grpc"
      OTEL_GRPC_ENDPOINT: "otel-collector:4317"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"
  
  app-b:
    build: ./fastapi_app/
    depends_on:
      - loki
    ports:
      - "8001:8000"
    logging: *default-logging
    environment:
      APP_NAME: "app-b"
      MODE: "otel-collector-http"
      OTEL_HTTP_ENDPOINT: "http://otel-collector:4318/v1/traces"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"
  
  app-c:
    build: ./fastapi_app/
    depends_on:
      - loki
    ports:
      - "8002:8000"
    environment:
      APP_NAME: "app-c"
      MODE: "jaeger-grpc"
      JAEGER_GRPC_ENDPOINT: "jaeger-collector:4317"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"

  app-d:
    build: ./fastapi_app/
    depends_on:
      - loki
    ports:
      - "8003:8000"
    logging: *default-logging
    environment:
      APP_NAME: "app-d"
      MODE: "jaeger-http"
      JAEGER_HTTP_ENDPOINT: "http://jaeger-collector:4318/v1/traces"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.47.0
    command: 
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
      - "--sampling.initial-sampling-probability=.5"
      - "--sampling.target-samples-per-second=.01"
      - "--collector.otlp.enabled=true"
    environment: 
      - SAMPLING_CONFIG_TYPE=adaptive
    ports:
      - "4317" # accept OpenTelemetry Protocol (OTLP) over gRPC
      - "4318" # accept OpenTelemetry Protocol (OTLP) over HTTP
      - "14250" # accept model.proto
    restart: on-failure
    depends_on:
      - cassandra-schema

  cassandra:
    image: cassandra:4.1.2

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:1.47.0
    depends_on:
      - cassandra

  jaeger-query:
    image: jaegertracing/jaeger-query:1.47.0
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
    ports:
      - "16686:16686"
      - "16687:16687"
    restart: on-failure
    depends_on:
      - cassandra-schema

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.81.0
    command:
      - "--config=/conf/config.yaml"
    volumes:
      - ./etc/otel-collector-config.yaml:/conf/config.yaml
    ports:
      - "4317" # OTLP gRPC receiver
      - "4318" # OTLP http receiver
    restart: on-failure
    depends_on:
      - jaeger-collector

  grafana:
    image: grafana/grafana:9.4.13
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"

  loki:
    image: grafana/loki:2.8.2
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
